# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js

node_js:
  - node
  - lts/*

sudo: false

branches:
  only:
    - master
    - dev

cache: yarn

before_install:
  # link missing node bin (for testing node CLI scripts)
  - sudo ln -s $(which node) /usr/bin/node && node -v
  # use newer version of yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

script:
  - yarn run lint
  - yarn run test-ci
  - codecov
