# Local MongoDB instance + web UI for development
#
# README:
#   To use this, first run the command:
#     docker stack deploy -c docker-compose.yml mongo
#
#   Then open a browser and go to:
#     http://localhost:8081
#
# NOTE:
#   Data is stored in a docker volume which can possibly be deleted and should
#   therfore be treated as ephemeral. Obviously, this is for development only.
#

version: '3.3'

services:
  mongo:
    image: mongo:3-jessie
    restart: on-failure
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VfwZ3NJraqIUXL1Va6nfoaiXqXH

  # FIXME: Doesn't support MongoDB 3.6 yet
  # mongo-express:
  #   image: mongo-express:latest
  #   restart: on-failure
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: VfwZ3NJraqIUXL1Va6nfoaiXqXH

volumes:
  db_data:
